# Generated by Django 6.0.7 on 2026-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist'), ('DOCTOR', 'Doctor'), ('LAB_ADMINISTRATOR', 'Lab Administrator')], default='RECEPTIONIST', max_length=20),
        ),
    ]
