# Generated by Django 6.0.7 on 2026-07-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist', '0011_alter_opdvisit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Laboratory Request',
                'verbose_name_plural': 'Laboratory Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('receptionist.opdvisit',),
        ),
    ]
