# Generated by Django 6.0.7 on 2026-07-16 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_labtest'),
        ('receptionist', '0013_hospitalsettings_free_followups_allowed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('bill_time', models.TimeField(auto_now_add=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_bills', to='receptionist.patient')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_bill', to='receptionist.opdvisit')),
            ],
            options={
                'verbose_name': 'Laboratory Bill',
                'verbose_name_plural': 'Laboratory Bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab.laboratorybill')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.labtest')),
            ],
        ),
    ]
