# Generated by Django 6.0.7 on 2026-07-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_laboratorybill_laboratorybillitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255, verbose_name='Parameter Name')),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='Unit')),
                ('reference_range', models.CharField(blank=True, max_length=255, verbose_name='Reference Range')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lab.labtest', verbose_name='Laboratory Test')),
            ],
            options={
                'verbose_name': 'Laboratory Test Parameter',
                'verbose_name_plural': 'Laboratory Test Parameters',
                'ordering': ['display_order', 'parameter_name'],
            },
        ),
    ]
