# Generated by Django 6.0.7 on 2026-07-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_labtestparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestparameter',
            name='parameter_type',
            field=models.CharField(blank=True, default='Numeric', max_length=100, verbose_name='Parameter Type'),
        ),
    ]
