# Generated by Django 6.0.7 on 2026-07-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_labtestparameter_parameter_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestparameter',
            name='reference_range',
        ),
        migrations.AddField(
            model_name='labtestparameter',
            name='common_reference_range',
            field=models.CharField(blank=True, max_length=255, verbose_name='Common Reference Range'),
        ),
        migrations.AddField(
            model_name='labtestparameter',
            name='female_reference_range',
            field=models.CharField(blank=True, max_length=255, verbose_name='Female Reference Range'),
        ),
        migrations.AddField(
            model_name='labtestparameter',
            name='male_reference_range',
            field=models.CharField(blank=True, max_length=255, verbose_name='Male Reference Range'),
        ),
    ]
