# Generated by Django 6.0.7 on 2026-07-16 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_remove_labtestparameter_reference_range_and_more'),
        ('receptionist', '0014_alter_opdvisit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=100, unique=True, verbose_name='Report Number')),
                ('generated_date', models.DateTimeField(auto_now_add=True, verbose_name='Generated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_reports', to='lab.labtest', verbose_name='Laboratory Test')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_reports', to='receptionist.patient', verbose_name='Patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_reports', to='receptionist.opdvisit', verbose_name='OPD Visit')),
            ],
            options={
                'verbose_name': 'Laboratory Report',
                'verbose_name_plural': 'Laboratory Reports',
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryReportResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(max_length=255, verbose_name='Result Value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_results', to='lab.labtestparameter', verbose_name='Parameter')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.laboratoryreport', verbose_name='Laboratory Report')),
            ],
            options={
                'verbose_name': 'Laboratory Report Result',
                'verbose_name_plural': 'Laboratory Report Results',
                'unique_together': {('report', 'parameter')},
            },
        ),
    ]
