# Generated by Django 6.0.7 on 2026-07-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_laboratoryreport_laboratoryreportresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryreport',
            name='report_number',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Report Number'),
        ),
    ]
