# Generated by Django 6.0.7 on 2026-07-17 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_alter_laboratoryreport_report_number'),
        ('receptionist', '0014_alter_opdvisit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SENT', 'Sent to Doctor')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='LaboratoryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_cases', to='receptionist.patient', verbose_name='Patient')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_case', to='receptionist.opdvisit', verbose_name='OPD Visit')),
            ],
            options={
                'verbose_name': 'Laboratory Case',
                'verbose_name_plural': 'Laboratory Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='laboratoryreport',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='lab.laboratorycase', verbose_name='Laboratory Case'),
        ),
    ]
