# Generated by Django 6.0.7 on 2026-07-14 21:55

import django.db.models.deletion
import doctor.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist', '0007_alter_opdvisit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandwrittenPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='High-quality PNG of the handwritten prescription.', upload_to=doctor.models.prescription_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='Doctor who wrote this prescription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient this prescription belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='handwritten_prescriptions', to='receptionist.patient')),
                ('visit', models.OneToOneField(help_text='OPD Visit this prescription is associated with. One per visit.', on_delete=django.db.models.deletion.PROTECT, related_name='handwritten_prescription', to='receptionist.opdvisit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
