# Generated by Django 6.0.7 on 2026-07-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrittenprescription',
            name='canvas_data',
            field=models.JSONField(blank=True, help_text='Strokes / JSON / vector data representing the editable master drawing.', null=True),
        ),
        migrations.AddField(
            model_name='handwrittenprescription',
            name='snapshot_data',
            field=models.JSONField(blank=True, help_text='Frozen metadata of patient, visit, vitals, doctor, and hospital settings at save time.', null=True),
        ),
    ]
