# Generated by Django 6.0.7 on 2026-07-15 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_handwrittenprescription_canvas_data_and_more'),
        ('receptionist', '0007_alter_opdvisit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HandwrittenPrescription',
            new_name='Prescription',
        ),
    ]
