# Generated by Django 6.0.7 on 2026-07-15 07:25

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_handwrittenprescription_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(help_text='High-quality PNG of the handwritten prescription.', max_length=500, upload_to=doctor.models.prescription_upload_path),
        ),
    ]
