# Generated by Django 6.0.7 on 2026-07-13 19:53

import django.core.validators
import django.db.models.deletion
import receptionist.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uhid', models.CharField(db_index=True, editable=False, help_text='Universal Health Identifier (Auto-generated)', max_length=20, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(validators=[receptionist.models.validate_dob_not_in_future])),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=10)),
                ('mobile_number', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OPDVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opd_number', models.CharField(db_index=True, editable=False, help_text='OPD Identifier (Auto-generated)', max_length=20, unique=True)),
                ('visit_date', models.DateField(db_index=True)),
                ('visit_time', models.TimeField()),
                ('visit_type', models.CharField(choices=[('New Visit', 'New Visit'), ('Follow-up', 'Follow-up')], max_length=20)),
                ('token_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('In Consultation', 'In Consultation'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_updated', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='receptionist.patient')),
            ],
            options={
                'ordering': ['-visit_date', '-visit_time'],
            },
        ),
    ]
