# Generated by Django 6.0.7 on 2026-07-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_hospitalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdvisit',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI')], default='Cash', max_length=10),
        ),
    ]
