# Generated by Django 6.0.7 on 2026-07-14 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0005_patientvitals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chief_complaint', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('heart_rate', models.IntegerField()),
                ('pulse_rate', models.IntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('spo2', models.IntegerField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_records', to='receptionist.patient')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='receptionist.opdvisit')),
            ],
            options={
                'verbose_name': 'Vitals',
                'verbose_name_plural': 'Vitals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PatientVitals',
        ),
    ]
