# Generated by Django 6.0.7 on 2026-07-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0007_alter_opdvisit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='bottle_feed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Whether the patient is on bottle feed', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in centimetres', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='pulse_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
