# Generated by Django 6.0.7 on 2026-07-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0008_add_height_and_bottle_feed_to_vitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='Respiratory rate in breaths per minute', null=True),
        ),
    ]
