# Generated by Django 6.0.7 on 2026-07-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0010_alter_opdvisit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdvisit',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Ready for Doctor', 'Ready for Doctor'), ('In Consultation', 'In Consultation'), ('Lab Requested', 'Lab Requested'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20),
        ),
    ]
