# Generated by Django 6.0.7 on 2026-07-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0012_alter_opdvisit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsettings',
            name='free_followups_allowed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='opd_validity_days',
            field=models.IntegerField(default=10),
        ),
    ]
