# Generated by Django 6.0.7 on 2026-07-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0013_hospitalsettings_free_followups_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdvisit',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Ready for Doctor', 'Ready for Doctor'), ('In Consultation', 'In Consultation'), ('Pending Lab', 'Pending Lab'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('IPD Recommended', 'IPD Recommended'), ('Discharged', 'Discharged')], default='Waiting', max_length=20),
        ),
    ]
