# Generated by Django 6.0.7 on 2026-07-18

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receptionist', '0014_alter_opdvisit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDAdmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_date', models.DateField(db_index=True)),
                ('admission_time', models.TimeField()),
                ('ward_type', models.CharField(max_length=50)),
                ('room_number', models.CharField(blank=True, null=True, max_length=20)),
                ('bed_number', models.CharField(blank=True, null=True, max_length=20)),
                ('diagnosis', models.TextField()),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=3000.00, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('receipt_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='Admitted', max_length=20)),
                ('has_warmer', models.BooleanField(default=False)),
                ('has_monitor', models.BooleanField(default=False)),
                ('has_hfnc', models.BooleanField(default=False)),
                ('has_ventilator', models.BooleanField(default=False)),
                ('has_infusion_pump', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitting_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions_admitted', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions', to='receptionist.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions', to='receptionist.opdvisit')),
            ],
            options={
                'ordering': ['-admission_date', '-admission_time'],
            },
        ),
        migrations.CreateModel(
            name='IPDBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('room_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('service_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('nursing_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('biomedical_waste_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('other_daily_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('injection_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('doctor_visit_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('emergency_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('visiting_doctor_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('physiotherapy_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('oxygen_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('misc_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('lab_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('radiology_charges', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=3000.00, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_time', models.TimeField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('receptionist_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='receptionist.ipdadmission')),
            ],
        ),
    ]
