# Generated by Django 6.0.7 on 2026-07-18

from django.db import migrations, models
import django.db.models.deletion

def populate_ipd_master_data(apps, schema_editor):
    WardMaster = apps.get_model('receptionist', 'WardMaster')
    RoomMaster = apps.get_model('receptionist', 'RoomMaster')
    BedMaster = apps.get_model('receptionist', 'BedMaster')
    IPDChargeMaster = apps.get_model('receptionist', 'IPDChargeMaster')

    # Wards
    wards_data = [
        'General Ward 1',
        'General Ward 2',
        'Private Ward',
        'Deluxe Ward',
        'PICU',
        'NICU',
    ]
    wards = {}
    for name in wards_data:
        wards[name], _ = WardMaster.objects.get_or_create(name=name)

    # Rooms
    # General Ward 1 & 2 -> Hall
    RoomMaster.objects.get_or_create(ward=wards['General Ward 1'], room_number='General Ward 1', room_type='Hall', capacity=20)
    RoomMaster.objects.get_or_create(ward=wards['General Ward 2'], room_number='General Ward 2', room_type='Hall', capacity=20)

    # Private Ward -> 101, 102, 103, 104, 105, 201
    for r_num in ['101', '102', '103', '104', '105', '201']:
        RoomMaster.objects.get_or_create(ward=wards['Private Ward'], room_number=r_num, room_type='Room', capacity=1)

    # Deluxe Ward -> 202, 203, 204
    for r_num in ['202', '203', '204']:
        RoomMaster.objects.get_or_create(ward=wards['Deluxe Ward'], room_number=r_num, room_type='Room', capacity=1)

    # PICU & NICU -> Hall with capacity=5
    picu_hall, _ = RoomMaster.objects.get_or_create(ward=wards['PICU'], room_number='Hall', room_type='Hall', capacity=5)
    nicu_hall, _ = RoomMaster.objects.get_or_create(ward=wards['NICU'], room_number='Hall', room_type='Hall', capacity=5)

    # Beds for PICU and NICU
    for i in range(1, 6):
        BedMaster.objects.get_or_create(room=picu_hall, bed_number=f"Bed {i}")
        BedMaster.objects.get_or_create(room=nicu_hall, bed_number=f"Bed {i}")

    # Charge Master entries
    charges = [
        ('REG', 'Registration Charge', 'One Time', 100.00),
        ('WARD_GEN', 'General Ward', 'Per Day', 600.00),
        ('WARD_PRI', 'Private Ward', 'Per Day', 1200.00),
        ('WARD_DEL', 'Deluxe Ward', 'Per Day', 2000.00),
        ('WARD_PICU', 'PICU', 'Per Day', 1000.00),
        ('WARD_NICU', 'NICU', 'Per Day', 1000.00),
        ('SERVICE', 'Service Charge', 'Per Day', 200.00),
        ('NURSING', 'Nursing Charge', 'Per Day', 400.00),
        ('BMW', 'Biomedical Waste', 'Per Day', 100.00),
        ('DOC_VISIT', 'Doctor Visit', 'Per Visit', 400.00),
        ('DOC_VISIT_SR', 'Doctor Visit (Senior)', 'Per Visit', 500.00),
        ('INJECTION', 'Injection / IV Charge', 'Per Injection', 30.00),
        ('EMERGENCY', 'Emergency Charge', 'One Time', 500.00),
        ('EMERGENCY_CRIT', 'Emergency Charge (Critical)', 'One Time', 1000.00),
        ('PHYSIO', 'Physiotherapy', 'Per Hour', 100.00),
        ('OXYGEN', 'Oxygen', 'Per Hour', 100.00),
        ('WARMER', 'Warmer', 'Per Day', 1000.00),
        ('INFUSION_PUMP', 'Infusion Pump', 'Per Day', 300.00),
        ('MONITOR', 'Multipara Monitor', 'Per Day', 500.00),
        ('HFNC', 'HFNC', 'Per Day', 1000.00),
        ('VENTILATOR', 'Ventilator', 'Per Day', 2000.00),
        ('AC', 'A/C Charge', 'Per Day', 800.00),
        ('VISITING_DOC', 'Visiting Doctor', 'Per Visit', 500.00),
    ]

    for code, name, c_type, amt in charges:
        IPDChargeMaster.objects.get_or_create(code=code, defaults={'name': name, 'charge_type': c_type, 'amount': amt})

def rollback_ipd_master_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0015_ipd_admission_and_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('Room', 'Room'), ('Hall', 'Hall')], default='Room', max_length=20)),
                ('capacity', models.IntegerField(default=1)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='receptionist.wardmaster')),
            ],
            options={
                'unique_together': {('ward', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='BedMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50)),
                ('is_occupied', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='receptionist.roommaster')),
            ],
            options={
                'unique_together': {('room', 'bed_number')},
            },
        ),
        migrations.CreateModel(
            name='IPDChargeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('charge_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RunPython(populate_ipd_master_data, rollback_ipd_master_data),
    ]
