# Generated by Django 6.0.7 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0016_ipd_master_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipdchargemaster',
            options={'verbose_name': 'IPD Charge / Rate Master', 'verbose_name_plural': 'IPD Charge / Rate Masters'},
        ),
        migrations.AddField(
            model_name='ipdchargemaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ipdchargemaster',
            name='unit',
            field=models.CharField(blank=True, default='Per Day', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ipdchargemaster',
            name='ward',
            field=models.CharField(blank=True, choices=[('General Ward', 'General Ward'), ('NICU', 'NICU'), ('PICU', 'PICU'), ('Private', 'Private'), ('Deluxe', 'Deluxe'), ('All Wards', 'All Wards')], default='General Ward', max_length=100, null=True),
        ),
    ]
