# Generated by Django 6.0.7 on 2026-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0017_alter_ipdchargemaster_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdadmission',
            name='diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='opdvisit',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Ready for Doctor', 'Ready for Doctor'), ('In Consultation', 'In Consultation'), ('Pending Lab', 'Pending Lab'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('IPD Recommended', 'IPD Recommended'), ('Admitted', 'Admitted'), ('Ready for Billing', 'Ready for Billing'), ('Discharged', 'Discharged')], default='Waiting', max_length=20),
        ),
        migrations.DeleteModel(
            name='IPDBill',
        ),
    ]
