# Generated by Django 6.0.7 on 2026-07-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0020_ipdbill_finalized_at_ipdbill_finalized_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdadmission',
            name='payment_mode',
            field=models.CharField(blank=True, default='Cash', max_length=20, null=True),
        ),
    ]
