# Generated by Django 6.0.7 on 2026-07-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0021_ipdadmission_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdbill',
            name='payment_mode',
            field=models.CharField(blank=True, default='Cash', max_length=20, null=True),
        ),
    ]
